const WARD_WHATSAPP='91XXXXXXXXXX'; // Replace before deployment.
const STORAGE_KEY='ward44_complaints_demo_v1';
let imageFiles=[], videoFile=null;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=t=>t?new Date(t).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—';
function getComplaints(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return[]}}
function saveComplaints(v){localStorage.setItem(STORAGE_KEY,JSON.stringify(v))}
function nextId(){const y=new Date().getFullYear();const count=getComplaints().filter(c=>String(c.complaint_no).startsWith(`W44-${y}-`)).length+1;return `W44-${y}-${String(count).padStart(4,'0')}`}
function publicComplaint(c){return {...c,images:[],video:null}}
const gpsBtn=$('getGps');if(gpsBtn)gpsBtn.onclick=()=>{const st=$('gpsStatus');if(!navigator.geolocation){st.textContent='GPS is not supported by this browser.';return}st.textContent='Getting GPS…';navigator.geolocation.getCurrentPosition(p=>{$('latitude').value=p.coords.latitude.toFixed(6);$('longitude').value=p.coords.longitude.toFixed(6);$('gpsAccuracy').value=Math.round(p.coords.accuracy);st.textContent=`GPS captured ±${Math.round(p.coords.accuracy)} m`},e=>st.textContent=e.code===1?'GPS permission denied. Please allow location.':'GPS unavailable. You can submit without GPS.',{enableHighAccuracy:true,timeout:7000,maximumAge:60000})};
function showFiles(){$('imageName').textContent=imageFiles.length?`${imageFiles.length} image(s) selected`:'No files chosen';$('videoName').textContent=videoFile?`${videoFile.name} (not stored online yet)`:'No file chosen';const box=$('mediaPreview');box.innerHTML='';imageFiles.forEach(f=>box.innerHTML+=`<img src="${URL.createObjectURL(f)}" alt="Issue image">`);if(videoFile)box.innerHTML+=`<video src="${URL.createObjectURL(videoFile)}" controls></video>`)}
$('imageInput').onchange=e=>{imageFiles=[...e.target.files].slice(0,5);showFiles()};$('videoInput').onchange=e=>{videoFile=e.target.files[0]||null;showFiles()};
$('complaintForm').onsubmit=e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;btn.textContent='Registering…';const fd=new FormData(e.target);const c={id:crypto.randomUUID(),complaint_no:nextId(),name:fd.get('name'),mobile:fd.get('mobile'),location:fd.get('location'),category:fd.get('category'),description:fd.get('description'),latitude:fd.get('latitude')||'',longitude:fd.get('longitude')||'',gps_accuracy:fd.get('gpsAccuracy')||'',status:'Registered',registered_at:new Date().toISOString(),updated_at:new Date().toISOString(),solved_at:null,media_note:(imageFiles.length||videoFile)?'Selected media is available only in this browser session; online media backup is not configured yet.':''};const all=getComplaints();all.unshift(publicComplaint(c));saveComplaints(all);$('newId').textContent=c.complaint_no;$('successBox').classList.remove('hidden');e.target.reset();imageFiles=[];videoFile=null;showFiles();if(!WARD_WHATSAPP.includes('X')){const text=`JAN SEVA YOJANA - WARD NO. 44\nNew Citizen Issue\nComplaint ID: ${c.complaint_no}\nParishad: Moinuddin Shaikh\nResident: ${c.name}\nMobile: ${c.mobile}\nLocation: ${c.location}\nCategory: ${c.category}\nProblem: ${c.description}\nStatus: Registered\nYour Problem will solve Within 3 to 7 Days.`;window.open(`https://wa.me/${WARD_WHATSAPP}?text=${encodeURIComponent(text)}`,'_blank')}$('successBox').scrollIntoView({behavior:'smooth',block:'center'});btn.disabled=false;btn.textContent='➤  Submit Complaint';refresh()};
$('waChat').onclick=()=>{if(WARD_WHATSAPP.includes('X')){alert('Set the Ward WhatsApp number in app.js first.');return}window.open(`https://wa.me/${WARD_WHATSAPP}?text=${encodeURIComponent('Hello Moinuddin Shaikh, I want to register an issue for Ward No. 44, Indra Colony, Pali.')}`,'_blank')};
function trackCurrent(show=false){const id=$('trackId').value.trim().toUpperCase(),box=$('trackResult');if(!id)return;if(show)box.innerHTML='<div class="result">Checking…</div>';const c=getComplaints().find(x=>x.complaint_no===id);if(!c){box.innerHTML='<div class="result">Complaint not found on this browser. The current version stores demo data locally; online shared storage will be connected later.</div>';return}const gps=c.latitude&&c.longitude?`${c.latitude}, ${c.longitude}`:'Not captured';box.innerHTML=`<div class="result"><b>${esc(c.complaint_no)} · ${esc(c.category)}</b><br>${esc(c.location)}<br>Status: <strong>${esc(c.status)}</strong><br>Registered: ${fmt(c.registered_at)}<br>GPS: ${esc(gps)}<br>Solved: ${fmt(c.solved_at)}<br><span>Your Problem will solve Within 3 to 7 Days.</span>${c.media_note?`<br><small>${esc(c.media_note)}</small>`:''}</div>`}
$('trackBtn').onclick=()=>trackCurrent(true);
function refresh(){const recent=getComplaints().slice(0,5);const el=$('recentList');if(!el)return;el.innerHTML=recent.length?recent.map(c=>`<div class="recent-item"><b>${esc(c.complaint_no)}</b><span>${esc(c.category)}</span><small>${esc(c.status)} · ${esc(fmt(c.registered_at))}</small></div>`).join(''):'<div class="result">No complaints yet on this browser.</div>'}
const viewAll=$('viewAll');if(viewAll)viewAll.onclick=()=>{location.hash='track';$('trackId').focus()};
refresh();
