// Set this after deploying Google Apps Script. Leave blank only for local demo mode.
const API_URL = 'https://script.google.com/macros/s/AKfycbzlzY7ESVKgJ_yjm2yKHorUM8szJYJdcZt0vBZBEMM7h8P_0X63RkPOPWncqx2XtZyT/exec';
const DEMO_KEY='ward44_demo_v2';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=t=>t?new Date(t).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—';
function demo(){try{return JSON.parse(localStorage.getItem(DEMO_KEY)||'[]')}catch{return[]}}
function saveDemo(v){localStorage.setItem(DEMO_KEY,JSON.stringify(v))}
function nextId(){const y=new Date().getFullYear();return `W44-${y}-${String(demo().length+1).padStart(4,'0')}`}
async function api(body){const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)});const text=await r.text();let j;try{j=JSON.parse(text)}catch{throw new Error('Invalid response from Google Apps Script')}if(!r.ok||!j.ok)throw new Error(j.message||'Server error');return j}
$('getGps').onclick=()=>{const s=$('gpsStatus');if(!navigator.geolocation){s.textContent='GPS is not supported.';return}s.textContent='Capturing GPS…';navigator.geolocation.getCurrentPosition(p=>{$('latitude').value=p.coords.latitude.toFixed(6);$('longitude').value=p.coords.longitude.toFixed(6);$('gpsAccuracy').value=Math.round(p.coords.accuracy);s.textContent=`GPS captured ±${Math.round(p.coords.accuracy)} m`},()=>s.textContent='GPS permission denied or unavailable.',{enableHighAccuracy:true,timeout:8000,maximumAge:60000})};
$('complaintForm').onsubmit=async e=>{e.preventDefault();const btn=$('submitBtn');btn.disabled=true;btn.textContent='Registering…';const fd=new FormData(e.target);const c={action:'create',name:fd.get('name'),mobile:fd.get('mobile'),location:fd.get('location'),category:fd.get('category'),priority:fd.get('priority'),description:fd.get('description'),latitude:fd.get('latitude'),longitude:fd.get('longitude'),gpsAccuracy:fd.get('gpsAccuracy')};try{const result=await api(c);$('newId').textContent=result.complaintId;$('successBox').classList.remove('hidden');e.target.classList.add('hidden');window.scrollTo({top:$('register').offsetTop-20,behavior:'smooth'});alert('Complaint registered successfully.');}catch(err){alert('Complaint could not be registered. Please try again.');console.error(err)}finally{btn.disabled=false;btn.innerHTML='Submit Complaint <span>→</span>'}};
$('newComplaint').onclick=()=>{$('successBox').classList.add('hidden');$('complaintForm').classList.remove('hidden');$('complaintForm').reset();$('gpsStatus').textContent='Location not captured';window.scrollTo({top:$('register').offsetTop-20,behavior:'smooth'})};
$('trackBtn').onclick=async()=>{const id=$('trackId').value.trim().toUpperCase();const box=$('trackResult');if(!id){box.innerHTML='<div class="result">Please enter a Complaint ID.</div>';return}box.innerHTML='<div class="result">Checking status…</div>';try{const r=await fetch(API_URL+'?action=track&id='+encodeURIComponent(id));const j=await r.json();if(!j.ok){box.innerHTML='<div class="result">Complaint not found.</div>';return}const c=j.complaint;box.innerHTML=`<div class="result"><b>${esc(c.complaintId)}</b><br><strong>${esc(c.category)}</strong> · ${esc(c.location)}<br>Status: <strong>${esc(c.status)}</strong><br>Registered: ${fmt(c.registeredAt||c.registered_at)}${c.latitude&&c.longitude?`<br><a class="map" target="_blank" href="https://www.google.com/maps?q=${encodeURIComponent(c.latitude+','+c.longitude)}">Open GPS location</a>`:''}<br><br>Your Problem will solve Within 3 to 7 Days.</div>`}catch(e){box.innerHTML='<div class="result">Unable to check status right now. Please try again.</div>'}};
$('waChat').onclick=e=>{e.preventDefault();const number='';if(!number){alert('WhatsApp number will be configured after the portal is connected.');return}window.open(`https://wa.me/${number}`,'_blank')};
